### ISSUE TITLE
Add version location of hexagon field

### ISSUE THREAD

**Issue by RuslanHale** [Rinat2050/Ants#13]
Making the location of hexagon field more logical.

**Comment by RuslanHale** [comment]
I'm still in the process
![image](https://github.com/Rinat2050/Ants/assets/142451436/3e9ca0fa-b4c0-4ffb-b2af-4603d548c6c6)

**Comment by KanVull** [comment]
What are those black dots and red dots means?
Can you provide a piece of code for this?
