### ISSUE TITLE
Add create_random_objects function

### ISSUE THREAD

**Issue by Rinat2050** [Rinat2050/Ants#15]
Создаём и раскидываем объекты по гексам случайным образом.

**Comment by KanVull** [comment]
Maybe, would it be better to name this kind of function something like `place_game_objects`.
Inside this function you can do something like create_objects (that'll do create_webs, .._spiders, ..etc.). But i think the creation and placement of objects are different functions by logic and would be better to separate those logic things

**Comment by KanVull** [comment]
Because, `create_random_objects` can return `1`, `Hello, world`, `Class::Web Object <#25377472636>` etc.
This name does not represent the main purpose of function that you want to realize
